# Generated by Django 3.0.5 on 2020-04-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='hello'),
            preserve_default=False,
        ),
    ]
