# Generated by Django 3.0.5 on 2020-04-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200408_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupon',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
